image: ubuntu:latest

before_script:
  # Run shell script for installing arduino-cli, Wio Terminal core, and project libraries
  - chmod +x setup-build-env.sh  # Change permissions to execute bash shell script
  - ./setup-build-env.sh  # Execute bash shell script
  - apt-get update -qq
  - apt-get install -y maven  # Maven installs

stages:
  - build_JavaFX
  - build_Arduino
  - deploy

# Arduino build job
compile_Arduino:
  stage: build_Arduino #define the stage for job
  tags:
    - docker #specifies to run on docker
  script:
    - apt-get update -qq
    - echo "Building Arduino project"
    - export PATH=$PATH:/root/bin  # Set the path to arduino-cli installation folder
    - pwd  # Print the current working directory
    - cd wioTerminal/envirobaby  # Change the directory to arduino folder
    - echo "$SECRETS_H" > Secrets.h  # Import secrets from GitLab CI/CD Settings -> Variables
    - arduino-cli lib list  # Check that libraries are installed
    # Compile
    - arduino-cli compile --fqbn Seeeduino:samd:seeed_wio_terminal
    # Upload
    - arduino-cli board list  # Check if device is connected
  except:
    - tags

# JavaFX build job
compile_JavaFX:
  stage: build_JavaFX #define the stage for job
  tags:
    - docker #specifies to run on docker
  script:
    - apt-get update -qq #package list is updated
    - apt-get install -y openjfx #openjfx dependencies are installed
    - echo "Building JavaFX project"
    - mvn clean compile
  except:
    - tags  # Build only on tag creation